name: Manual Build for ProVerBMate

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout ProVerBMate repository
        uses: actions/checkout@v3

      # Set Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      
      # Package the jar file
      - name: package
        run: |
          mvn package -DskipTests
          echo Maven package success

      #Upload ProVerBMate artifact
      - uses: actions/upload-artifact@v3
        with:
          name: ProVerBMate
          path: target/ProVerBMate-1.6.0.jar
          
      #Upload ProVerB's ontology file
      - uses: actions/upload-artifact@v3
        with:
          name: Ontology
          path: ProVerB_1.6.0.owl

      # Release
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GIT_API }}"
          automatic_release_tag: "manual"
          prerelease: false
          title: "${{ steps.date.outputs.date }}"
          files: |
            ProVerB_1.6.0.owl
            target/ProVerBMate-1.6.0.jar
